### ISSUE TITLE
请求结束后未关闭，response.Body.Close()

### ISSUE THREAD

**Issue by spadesk1991** [lxzan/hasaki#2]
![Snipaste_2021-01-05_16-11-42](https://user-images.githubusercontent.com/43500758/103621819-c087f880-4f70-11eb-88d7-fb67b1aba150.png)

**Comment by lxzan** [comment]
thanks for your issue

**Comment by lxzan** [comment]
> ![Snipaste_2021-01-05_16-11-42](https://user-images.githubusercontent.com/43500758/103621819-c087f880-4f70-11eb-88d7-fb67b1aba150.png)

最新版本的已经解决了

**Comment by lxzan** [comment]
最新版本的已经解决了
